apiVersion: extensions/v1beta1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: $name$
    labels:
      app: $label$
  spec:
    replicas: $replicas$
    selector:
      matchLabels:
        app: $label$
    template:
      metadata:
        labels:
          app: $label$
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values: $matchExpressions-values$
        containers:
          - name: $name$
            image: $image$
            #command: ["sh","-c"]
            #args: ["/usr/sbin/sshd -D"]
            command: $cmd$
            args: $args$
            volumeMounts:
              - name: nfs-storage
                readOnly: false
                mountPath: $nfspath$
            ports:
              - name: restserver
                containerPort: 8000
              - name: ssh
                containerPort: 22
            resources:
              limits:
                nvidia.com/gpu: $gpu$
                #alpha.kubernetes.io/nvidia-gpu: 1
                cpu: $cpu$
                memory: $memory$
              requests:
                nvidia.com/gpu: $gpu$
                cpu: $cpu$
                memory: $memory$
        volumes:
          - name: nfs-storage
            nfs:
              server: $nfsip$
              path: $nfspath$

- apiVersion: v1
  kind: Service
  metadata:
    name: $name$
  spec:
    externalIPs:
     - $externalIPs$
#    type: NodePort
    selector:
      app: $label$
    ports:
      - name: restserver
        port: $nodePort$
#        nodePort: $nodePort$
        targetPort: 8000
#        protocol: TCP
#      - name: ssh
#        port: 31003
#        nodePort: 31002
#        targetPort: 22
