#!/bin/bash

SERVER_EXEC=tensorrt_server
MODEL=$MODEL$
LABELS=$LABELS$
INPUT_NAME=data_0
OUTPUT_NAME=prob_1
INFER_DTYPE=float16

CMD="$SERVER_EXEC -t onnx -d $INFER_DTYPE -i $INPUT_NAME -o $OUTPUT_NAME -m $MODEL -l $LABELS"

echo
echo "================================================"
echo "$CMD"
echo "================================================"
exec $CMD
