#!/bin/bash

SERVER_EXEC=tensorrt_server
MODEL=$MODEL$
LABELS=$LABELS$
INPUT_NAME=input
INPUT_FORMAT=float32,3,224,224
OUTPUT_NAME=output
INFER_DTYPE=float16

CMD="$SERVER_EXEC -t tensorflow -d $INFER_DTYPE -i $INPUT_NAME -f $INPUT_FORMAT -o $OUTPUT_NAME -m $MODEL -l $LABELS"

echo
echo "================================================"
echo "$CMD"
echo "================================================"
exec $CMD
