#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        if [ -d /usr/share/hyperai/hyperai/jobs ]; then
            # Copy job data from previous install
            mkdir -p /var/lib/hyperai
            mv /usr/share/hyperai/hyperai/jobs /var/lib/hyperai/
        fi
        ;;

    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
