apiVersion: batch/v1
kind: $kind$
metadata:
  name: $metadata-name$
spec:
  template:
    metadata:
      labels:
        name: $labels-name$
        role: hyperaijob
    spec:
      containers:
        - name: $container-name$
          image: $image$
          command: $command$
          args: $args$
          env:
          - name: PROTOBUF_ROOT
            value: "/root/protobuf"
          - name: HYPERAI_ROOT
            value: "/root/hyperai"
          - name: CUDNN_VERSION
            value: "5.1.10"
          - name: NVIDIA_REQUIRE_CUDA
            value: "cuda>=8.0"
          - name: LIBRARY_PATH
            value: "/usr/local/cuda/lib64/stubs:"
          - name: LD_LIBRARY_PATH
            value: "/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility"
          - name: PATH
            value: "/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          - name: CUDA_PKG_VERSION
            value: "8-0=8.0.61-1"
          - name: CUDA_VERSION
            value: "8.0.61"
          - name: CAFFE_ROOT
            value: "/root/caffe/"
          - name: TORCH_ROOT
            value: "/root/torch/"
          - name: HYPERAI_JOBS_DIR
            value: $hyperai_jobs_dir$
          volumeMounts:
          - name: nfs-storage
            readOnly: false
            mountPath: $mountpath$
          resources:
            limits:
              nvidia.com/gpu: $gpu$
              cpu: $cpu$
              memory: $memory$
          ports:
          - name: tensorflow-1
            containerPort: 5000
          - name: tensorflow-2
            containerPort: 22
      restartPolicy: OnFailure
#      restartPolicy: Never
      volumes:
        - name: nfs-storage
          nfs:
            server: 10.18.95.2
            path: $nfspath$

