"""empty message

Revision ID: a8cd66420e23
Revises: 
Create Date: 2018-07-24 08:57:38.376091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cd66420e23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_user', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('apply_scenes', sa.String(length=64), nullable=False),
    sa.Column('data_num', sa.String(length=20), nullable=False),
    sa.Column('buy_num', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=False),
    sa.Column('data_type', sa.String(length=12), nullable=False),
    sa.Column('permissions', sa.Enum('U', 'D', 'S'), nullable=True),
    sa.Column('department', sa.String(length=24), nullable=True),
    sa.Column('dataset_path', sa.String(length=256), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('pic_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_permissions'), 'datasets', ['permissions'], unique=False)
    op.create_table('departments',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depart_name', sa.String(length=256), nullable=True),
    sa.Column('depart_power', sa.Integer(), nullable=True),
    sa.Column('gpu_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_user', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('apply_scenes', sa.String(length=256), nullable=False),
    sa.Column('framework', sa.String(length=20), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.String(length=10), nullable=False),
    sa.Column('buy_num', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=False),
    sa.Column('model_path', sa.String(length=256), nullable=False),
    sa.Column('permissions', sa.Enum('U', 'D', 'S'), nullable=True),
    sa.Column('department', sa.String(length=24), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_permissions'), 'models', ['permissions'], unique=False)
    op.create_table('monitor',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpu_utilization', sa.String(length=256), nullable=True),
    sa.Column('pod_name', sa.String(length=256), nullable=True),
    sa.Column('memory', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('real_name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.Column('integral', sa.Integer(), nullable=True),
    sa.Column('gpu_used', sa.Integer(), nullable=True),
    sa.Column('examined', sa.Boolean(), nullable=True),
    sa.Column('release', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comments',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_name', sa.String(length=32), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_to_dataset',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_to_department',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_to_model',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_model')
    op.drop_table('user_to_department')
    op.drop_table('user_to_dataset')
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('monitor')
    op.drop_index(op.f('ix_models_permissions'), table_name='models')
    op.drop_table('models')
    op.drop_table('departments')
    op.drop_index(op.f('ix_datasets_permissions'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
