apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $name$
  labels:
    app: $label$
spec:
  replicas: $node_count$
  template:
    metadata:
      labels:
        app: $label$
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: $matchExpressions-values$
      containers:
      - image: $image$
        name : $name$
        resources:
          limits:
            cpu: $cpu$ 
            memory: $memory$ 
            nvidia.com/gpu: $gpu$
          requests:
            cpu: $cpu$ 
            memory: $memory$ 
            nvidia.com/gpu: $gpu$
        command: $cmd$
        args: $args$
        volumeMounts:
          - name: nfs-storage
            readOnly: false
            mountPath: "/home/newnfs"
#            mountPath: $nfspath$
        env:
          - name: LD_LIBRARY_PATH
            value: "/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/lib"
          - name: MXNET_ENABLE_GPU_P2P
            value: "0"
      volumes:
        - name: nfs-storage
          nfs:
            server: $nfsip$
            path: $nfspath$

