apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $name$
  labels:
    app: $label$
spec:
  replicas: $node_count$
  template:
    metadata:
      labels:
        app: $label$
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: $matchExpressions-values$
      containers:
      - image: $image$
        name : $name$
        resources:
          limits:
            cpu: $cpu$ 
            memory: $memory$ 
            nvidia.com/gpu: $gpu$
          requests:
            cpu: $cpu$ 
            memory: $memory$ 
            nvidia.com/gpu: $gpu$
        command: ['/usr/sbin/sshd']
        args: ['-D']
        volumeMounts:
          - name: nfs-storage
            readOnly: false
            mountPath: "/home/newnfs"
#            mountPath: $nfspath$
      volumes:
        - name: nfs-storage
          nfs:
            server: $nfsip$
            path: $nfspath$

