apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $name$
  labels:
    app: $label$
spec:
  replicas: $node_count$
  template:
    metadata:
      labels:
        app: $label$
    spec:
#      nodeSelector:
#          kubernetes.io/hostname: $select_node$
      containers:
      - image: $image$
        name : $name$
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 4
            memory: 8Gi
        command: ['/usr/sbin/sshd']
        args: ['-D']
        volumeMounts:
          - name: nfs-storage
            readOnly: false
            mountPath: "/home/nfsdir"
#            mountPath: $nfsip$
      volumes:
        - name: nfs-storage
          nfs:
            server: $nfsip$
            path: $nfsip$

